version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ~/connect_four/db:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - 80:80
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432
    depends_on:
      - db